### PR TITLE
Modified Protein normalization function 

### PR DESCRIPTION
**Pull request by jlrestrepol**
Changed the Protein Normalization function of the cite_utils.py file and verified that it reproduces the results of that in the Protein Normalization nb.

### CODE REVIEW

**Comment by jlrestrepol** [comment]
@Marius1311 Please review for merging.

**Comment by Marius1311** [comment]
Sorry @jlrestrepol , I got kind of confused and just saw this now - everything worked as it should, I also got a notification. 

Please, in the protein normalisation function, keep the option to normalise by the clr (centered log ratio) and log transform only if that option is chosen. (method='clr')

**Comment by jlrestrepol** [comment]
@Marius1311 I added the changes and pushed my local branch. I think that's all for you to be able to see the changes in this PR, right?

**Comment by Marius1311** [comment]
Hi Juan! Yes, I can see the changes, thanks! Can you add an additional function to log-transform the proteins (incase somone did not chose clr to normalise), analogous to sc.pp.log1p (add one and log transform, only the proteins, not bad_struct etc.)

**Comment by jlrestrepol** [comment]
@Marius1311 done!

**Review by Marius1311 — APPROVED** [review]

**Pull request merged**
